/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.servicioselectricosmya.view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import ucr.ac.cr.servicioselectricosmya.model.Bill;

/**
 *
 * @author Stephanie
 */
public class DataPanelBill extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelBill
     */
    public DataPanelBill() {
        initComponents();
    }

    public void listen(ActionListener controller) {
        this.btnCalculate.addActionListener(controller);
    }

    public void setLbTotalPay(double totalPay) {
        this.lbTotalPay.setText(Double.toString(totalPay));
    }

    public int getLbNumberBill() {

        return Integer.parseInt(lbNumberBill.getText());
    }

    public int getEnergyComsumption() {
        return Integer.parseInt(this.spElectricConsumption.getValue().toString());
    }

    public void clear() {

        this.cbxElectricMeterNumber.setSelectedIndex(0);
        this.txtDate.setText("");
        this.spElectricConsumption.setValue(1);
        this.lbTotalPay.setText("00");
    }

    public Bill getBill() {
        try {
            return new Bill(Integer.parseInt(this.lbNumberBill.getText()),
                    Integer.parseInt(this.cbxElectricMeterNumber.getSelectedItem().toString()),
                    this.txtDate.getText(),
                    Integer.parseInt(this.spElectricConsumption.getValue().toString()),
                    Double.parseDouble(this.lbTotalPay.getText()));
        } catch (NumberFormatException e) {
            return new Bill();
        }
    }

    public void setBill(Bill bill) {
        this.lbNumberBill.setText(String.valueOf(bill.getBillNumber()));
        this.cbxElectricMeterNumber.setSelectedItem(bill.getElectricMeterNumber());
        this.txtDate.setText(bill.getDate());
        this.spElectricConsumption.setValue(bill.getEnergyConsumption());
        this.lbTotalPay.setText(String.valueOf(bill.getTotalPay()));
    }

    public void setTotalPay(String totalPay) {
        this.lbTotalPay.setText(totalPay);
    }

    public void setNumberBill(String numberBill) {
        this.lbNumberBill.setText(numberBill);
    }

    public void setCbMeterNumbers(String[] list) {
        DefaultComboBoxModel model = new DefaultComboBoxModel(list);
        this.cbxElectricMeterNumber.setModel(model);
        this.cbxElectricMeterNumber.insertItemAt("Select option", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNumberBill = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxElectricMeterNumber = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        spElectricConsumption = new javax.swing.JSpinner();
        lbTotalPay = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setText("Bills Record");

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel2.setText("Number bill:");

        lbNumberBill.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        lbNumberBill.setText("0000");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("Electric meter number");

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel6.setText("Electric consumption");

        jLabel7.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel7.setText("Total to pay");

        cbxElectricMeterNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spElectricConsumption.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lbTotalPay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTotalPay.setText("00.00");

        btnCalculate.setText("Calculate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(40, 40, 40)
                                .addComponent(spElectricConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lbTotalPay)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalculate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(cbxElectricMeterNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNumberBill)))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbNumberBill))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxElectricMeterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spElectricConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbTotalPay)
                    .addComponent(btnCalculate))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cbxElectricMeterNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbNumberBill;
    private javax.swing.JLabel lbTotalPay;
    private javax.swing.JSpinner spElectricConsumption;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
