/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.servicioselectricosmya.view;

/**
 *
 * @author Stephanie
 */
public class GUIBill extends javax.swing.JFrame {

    /**
     * Creates new form GUIBill
     */
    public GUIBill() {
        initComponents();
    }

    public DataPanelBill getDataPanelBill1() {
        return dataPanelBill1;
    }

    public PanelButtons getPanelButtons1() {
        return panelButtons1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButtons1 = new ucr.ac.cr.servicioselectricosmya.view.PanelButtons();
        dataPanelBill1 = new ucr.ac.cr.servicioselectricosmya.view.DataPanelBill();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelButtons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 420, 140));
        getContentPane().add(dataPanelBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.servicioselectricosmya.view.DataPanelBill dataPanelBill1;
    private ucr.ac.cr.servicioselectricosmya.view.PanelButtons panelButtons1;
    // End of variables declaration//GEN-END:variables
}
