/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.servicioselectricosmya.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Stephanie
 */
public class GUIClient extends javax.swing.JFrame {

    /**
     * Creates new form GUIClient
     */
    public GUIClient() {
        initComponents();
    }

    public static void setMessage(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    public DataPanelClient getDataPanelClient1() {
        return dataPanelClient1;
    }

    public PanelButtons getPanelButtons1() {
        return panelButtons1;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButtons1 = new ucr.ac.cr.servicioselectricosmya.view.PanelButtons();
        dataPanelClient1 = new ucr.ac.cr.servicioselectricosmya.view.DataPanelClient();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelButtons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 140));
        getContentPane().add(dataPanelClient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.servicioselectricosmya.view.DataPanelClient dataPanelClient1;
    private ucr.ac.cr.servicioselectricosmya.view.PanelButtons panelButtons1;
    // End of variables declaration//GEN-END:variables
}
